class StockDashboard {
    // ... existing code ...

    async loadData() {
        try {
            // Load from the JSON file generated by GitHub Actions
            const response = await fetch('data/processed/latest_stocks.json');
            if (response.ok) {
                const data = await response.json();
                this.stocks = data.stocks;
                this.lastUpdated = data.last_updated;
            } else {
                throw new Error('No data file found');
            }
        } catch (error) {
            console.log('Using sample data:', error);
            this.stocks = SAMPLE_DATA.stocks;
            this.lastUpdated = new Date().toISOString();
            document.getElementById('error-message').style.display = 'block';
        }
        
        this.filteredStocks = [...this.stocks];
        this.updateLastUpdated();
    }

    updateLastUpdated() {
        const updateTime = document.getElementById('update-time');
        if (this.lastUpdated) {
            const date = new Date(this.lastUpdated);
            updateTime.textContent = date.toLocaleString('en-US', { 
                weekday: 'short',
                year: 'numeric',
                month: 'short',
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
            });
        } else {
            updateTime.textContent = 'Loading...';
        }
    }
}
